Controllers/CarController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace CarEngines.Controllers
{
    [Authorize]
    public class CarController : Controller
    {
        private readonly IMainRepository<Car> _carRepository;
        private readonly IMainRepository<Engine> _engineRepository;


        private Engine EngineModel { get; set; }

        public CarController(IMainRepository<Car> carRepository, IMainRepository<Engine> engineRepository)
        {
            _carRepository = carRepository;
            _engineRepository = engineRepository;
        }

        public IActionResult Index(int? id)
        {
            if (id != null)
            {
                var engine = _engineRepository.FindByID(id);
                var carsWithThisEngine = _carRepository.GetFullList().Where(e => e.Engine == engine);

                ViewBag.message = $"Cars with engine {engine.Brand}, capacity: {engine.Capacity_ccm} ccm";

                return View(carsWithThisEngine);
            }
            else
            {
                var allCarsInDb = _carRepository.GetFullList();
                ViewBag.message = "List of all cars";
                return View(allCarsInDb);
            }
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            var enginesList = _engineRepository.GetFullList();

            ViewBag.data = enginesList;
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create(Car car)
        {
            if (!ModelState.IsValid) return BadRequest();
            _carRepository.AddElement(car);
            _carRepository.Save();

            return RedirectToAction("Index", new { id = car.EngineId });
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(int? id)
        {
            if (id == null) return BadRequest();
            var carInDb = _carRepository.FindByID(id);
            if (carInDb == null) return BadRequest();

            var enginesList = _engineRepository.GetFullList();
            ViewBag.data = enginesList;

            return View(carInDb);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(Car car)
        {          
            if (!ModelState.IsValid) return BadRequest();
            _carRepository.UpdateElement(car);
            _carRepository.Save();

            return RedirectToAction("Index", new { id = car.EngineId });
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(int? id)
        {
            if (id == null) return BadRequest();
            var carInDb = _carRepository.FindByID(id);
            if (carInDb == null) return BadRequest();
            _carRepository.DeleteElement(carInDb);
            _carRepository.Save();

            return Redirect(Request.Headers["Referer"].ToString());
        }
    }
}

Controllers/EngineController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CarEngines.Controllers
{
    [Authorize]
    public class EngineController : Controller
    {
        private readonly IMainRepository<Engine> _engineRepository;             

        public EngineController(IMainRepository<Engine> engineRepository)
        {
            _engineRepository = engineRepository;
        }
       
        public IActionResult Index()
        {
            var enginesList = _engineRepository.GetFullList();
            return View(enginesList);
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create(Engine engine)
        {
            var engines = _engineRepository.GetFullList();
            if (!ModelState.IsValid) return BadRequest();           
            engines.Add(engine);
            _engineRepository.Save();
            return RedirectToAction("Index");                               
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(int? id)
        {
            if (id == null) return BadRequest();
            var engineInDb = _engineRepository.FindByID(id);
            if(engineInDb == null) return BadRequest();           
            return View(engineInDb);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(Engine engine)
        {            
            if (!ModelState.IsValid) return BadRequest();

            _engineRepository.UpdateElement(engine);
            _engineRepository.Save();
            return RedirectToAction("Index");
            
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(int? id)
        {
            if (id == null) return BadRequest();
            var engineInDb = _engineRepository.FindByID(id);
            if (engineInDb == null) return BadRequest();
            _engineRepository.DeleteElement(engineInDb);
            _engineRepository.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int? id)
        {            
            return RedirectToAction("Index", "Car", new { id = id });        
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarEngines</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @if (User.IsInRole("Administrator") || User.IsInRole("User"))
                {
                    <a class="navbar-brand" asp-route-id="" asp-controller="Engine" asp-action="Index">All engines</a>
                    <a class="navbar-brand" asp-route-id="" asp-controller="Car" asp-action="Index">All cars</a>
                }
                <a class="navbar-brand" asp-route-id="" asp-controller="Account" asp-action="Register">Register</a>
                <a class="navbar-brand" asp-route-id="" asp-controller="Account" asp-action="Login">Login</a>
                <a class="navbar-brand" asp-route-id="" asp-controller="Account" asp-action="Logout">Logout</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CarEngines
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>